apiVersion: v1
kind: Service
metadata:
  name: {{ include "lra.webhookName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "lra.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "lra.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: webhook
  ports:
    - name: https
      port: 443
      targetPort: webhook
